% New_scans_plot_all
% Produce the updated plots (16/6/17)
% Uses the results from Run_single_variable_scan.m to make the computational result
% Also uses the results from a composition scan
% This is generated by the function Deconvolute_composition_scan.m (which extends Process_composition_scan.m)
% N.b. electron density is manually hard coded in in Process_composition_scan.m (line 36)
% All subroutines and results are saved in OutputPlots

Computational_line_width = 2;
Experimental_line_width = 2;
Experimental_marker_size = 10;
Close_after_save = true;

MATLAB_colours = [         0    0.4470    0.7410; ...
    0.8500    0.3250    0.0980; ...
    0.9290    0.6940    0.1250; ...
    0.4940    0.1840    0.5560; ...
    0.4660    0.6740    0.1880; ...
    0.3010    0.7450    0.9330; ...
    0.6350    0.0780    0.1840];

FullWidthStyle = hgexport('readstyle','FullWidthFigure');
ColumnWidthStyle = hgexport('readstyle','ColumnWidthFigure');
% Save for replicability
save('OutputPlots/ExportStyles','FullWidthStyle','ColumnWidthStyle');

% Composition scans
FigureWidth_control = 'Full';
Comp_scan_plot_neutrals
    FullWidthStyle.Format = 'eps';
    hgexport(gcf,'OutputPlots/Composition_scan_neutrals.eps',FullWidthStyle);
    FullWidthStyle.Format = 'png';
    hgexport(gcf,'OutputPlots/Composition_scan_neutrals.png',FullWidthStyle);
    savefig(gcf,'OutputPlots/Composition_scan_neutrals.fig')
    if Close_after_save
        close(neutral_figure);
        clear('neutral_figure');
    end

Comp_scan_plot_ions
    FullWidthStyle.Format = 'eps';
    hgexport(gcf,'OutputPlots/Composition_scan_ions.eps',FullWidthStyle);
    FullWidthStyle.Format = 'png';
    hgexport(gcf,'OutputPlots/Composition_scan_ions.png',FullWidthStyle);
    savefig(gcf,'OutputPlots/Composition_scan_ions.fig')
    if Close_after_save
        close(ion_figure);
        clear('ion_figure');
    end

FigureWidth_control = 'Column';
Comp_scan_plot_surface
    ColumnWidthStyle.Format = 'eps';
    hgexport(gcf,'OutputPlots/Composition_scan_surface.eps',ColumnWidthStyle);
    ColumnWidthStyle.Format = 'png';
    hgexport(gcf,'OutputPlots/Composition_scan_surface.png',ColumnWidthStyle);
    savefig(gcf,'OutputPlots/Composition_scan_surface.fig')
    if Close_after_save
        close(surface_figure);
        clear('surface_figure');
    end

Comp_scan_plot_fractions
    ColumnWidthStyle.Format = 'eps';
    hgexport(gcf,'OutputPlots/Composition_scan_fraction.eps',ColumnWidthStyle);
    ColumnWidthStyle.Format = 'png';
    hgexport(gcf,'OutputPlots/Composition_scan_fraction.png',ColumnWidthStyle);
    savefig(gcf,'OutputPlots/Composition_scan_fraction.fig')
    if Close_after_save
        close(fractions_figure);
        clear('fractions_figure');
    end

FigureWidth_control = 'Full';
Comp_scan_plot_reactions
    FullWidthStyle.Format = 'eps';
    hgexport(gcf,'OutputPlots/Composition_scan_reaction.eps',FullWidthStyle);
    FullWidthStyle.Format = 'png';
    hgexport(gcf,'OutputPlots/Composition_scan_reaction.png',FullWidthStyle);
    savefig(gcf,'OutputPlots/Composition_scan_reaction.fig')
    if Close_after_save
        close(reaction_figure);
        clear('reaction_figure');
    end

% Power scans
FigureWidth_control = 'Full';
Power_scan_plot_neutrals
    FullWidthStyle.Format = 'eps';
    hgexport(gcf,'OutputPlots/Power_scan_neutrals.eps',FullWidthStyle);
    FullWidthStyle.Format = 'png';
    hgexport(gcf,'OutputPlots/Power_scan_neutrals.png',FullWidthStyle);
    savefig(gcf,'OutputPlots/Power_scan_neutrals.fig')
    if Close_after_save
        close(neutral_figure_p);
        clear('neutral_figure_p');
    end
Power_scan_plot_ions
    FullWidthStyle.Format = 'eps';
    hgexport(gcf,'OutputPlots/Power_scan_ions.eps',FullWidthStyle);
    FullWidthStyle.Format = 'png';
    hgexport(gcf,'OutputPlots/Power_scan_ions.png',FullWidthStyle);
    savefig(gcf,'OutputPlots/Power_scan_ions.fig')
    if Close_after_save
        close(ion_figure_p);
        clear('ion_figure_p');
    end
FigureWidth_control = 'Column';
Power_scan_plot_surface
    ColumnWidthStyle.Format = 'eps';
    hgexport(gcf,'OutputPlots/Power_scan_surface.eps',ColumnWidthStyle);
    ColumnWidthStyle.Format = 'png';
    hgexport(gcf,'OutputPlots/Power_scan_surface.png',ColumnWidthStyle);
    savefig(gcf,'OutputPlots/Power_scan_surface.fig')
    if Close_after_save
        close(surface_figure_p);
        clear('surface_figure_p');
    end
Power_scan_plot_fractions
    ColumnWidthStyle.Format = 'eps';
    hgexport(gcf,'OutputPlots/Power_scan_fraction.eps',ColumnWidthStyle);
    ColumnWidthStyle.Format = 'png';
    hgexport(gcf,'OutputPlots/Power_scan_fraction.png',ColumnWidthStyle);
    savefig(gcf,'OutputPlots/Power_scan_fraction.fig')
    if Close_after_save
        close(fractions_figure_p);
        clear('fractions_figure_p');
    end

close hidden
clear('Controller')

disp('Done')

clear('Close_after_save', 'ColumnWidthStyle', 'Computational_line_width', 'Experimental_line_width', 'Experimental_marker_size', 'FigureWidth_control', 'FullWidthStyle', 'MATLAB_colours')