function Plotting_single_variable_scan(Test_name)
%% Function for plotting from a save-state generated by the
%% Run_single_variable_scan.m function
%% This function will save a .mat file with the following
%% variables --> (dims) <type>: description;
%% Number of species is S
%% Number of reactions is R
%% Number of tests is T
% Information storage
    % Controller --------> GUI_control object    : stored for compatibility (use Controller.show('on') to show)
    % Species_I2E -------> (S,1) <cell array>    : list of species keys
    % Reaction_I2E ------> (R,1) <cell array>    : list of reaction keys
% Scan results
    % Density -----------> (S,T) <vector double> : final density for species
    % DensityError ------> (S,T) <vector double> : error estimate on this result
    % Te ----------------> (1,T) <vector double> : final electron temperature
    % TeError -----------> (1,T) <vector double> : error estimate on this result
    % Rate --------------> (R,T) <vector double> : final evaluated rate coefficient
% Scan parameters
    % Scan_parameter ----> (1,1) <char string>   : 
    % Scan_values -------> (T,1) <vector double> : 
% System parameters (length will be T for the Scan_parameter, and 1 otherwise)
    % H2Supply ----------> (*,1) <vector double> : 
    % N2Supply ----------> (*,1) <vector double> : 
    % Power -------------> (*,1) <vector double> : 
    % Pressure ----------> (*,1) <vector double> : 

    load(Test_name)
    disp(Power)


    close all hidden %Delete the GUI controller if it is not shown
end